config/routes.rb
Rails.application.routes.draw do
  root to: "restaurants#home"
  resources :restaurants
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  validates :name, presence: true
  validates :address, presence: true
  validates :rating, inclusion: { in: 1..5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  def index
    if params[:query].present?
      @restaurants = Restaurant.where("city LIKE ?", "%#{params[:query]}%")
    else
      @restaurants = Restaurant.all
    end
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.save

    redirect_to restaurant_path(@restaurant)
  end

  def edit; end

  def update
    @restaurant.update(restaurant_params)

    redirect_to restaurant_path(@restaurant)
  end

  def destroy
    @restaurant.destroy

    redirect_to restaurants_path
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :city, :rating, :highlights)
  end

  def home; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AllRestaurants</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= form_for(@restaurant) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :address %>
  <%= f.text_field :address %>
  <%= f.label :city %>
  <%= f.text_field :city %>
  <%= f.label :rating %>
  <%= f.number_field :rating %>
  <%= f.label :highlights %>
  <%= f.text_field :highlights %>
  <%= f.submit %>
<% end %>

app/views/restaurants/edit.html.erb
<%= render "form", restaurant: @restaurant%>

app/views/restaurants/home.html.erb
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <div class="homepage-body-content">
    <div class="homepage-text">
      <h1>GRUB</h1>
      <h3>Find great eats from around the world! Choose a city, explore restaurant suggestions, and read about my personal favourite meals.</h3>
      <div class="center-homepage-button">
        <div class="homepage-button">
          <%= link_to "explore restaurants", restaurants_path %>
        </div>
      </div>
    </div>
  </div>
</body>
</html>

app/views/restaurants/index.html.erb
<h1> Restaurants</h1>
<%= form_tag restaurants_path, method: :get do %>
  <%= text_field_tag :query,
    params[:query],
    class: "form-control",
    placeholder: "Search by city"
  %>
  <%= submit_tag "Search", class: "btn btn-primary" %>
<% end %>
<div class="all-restaurants-grid">
  <div class="each-restaurant-grid">
    <%= link_to "+ new", new_restaurant_path %>
  </div>
  <% @restaurants.each do |restaurant| %>
    <div class="each-restaurant-grid">
      <%= link_to restaurant.name, restaurant_path(restaurant) %>
    </div>
  <% end %>
</div>

app/views/restaurants/new.html.erb
<%= render "form", restaurant: @restaurant%>

app/views/restaurants/show.html.erb
<h2><%= @restaurant.name %> - <%= @restaurant.rating %></h2>
<h3><%= @restaurant.address %></h3>
<h4><%= @restaurant.city %></h4>
<h4><%= @restaurant.highlights %></h4>
<h4><%= "never been" if !@restaurant.verified %></h4>

<%= link_to "back", restaurants_path %>
<%= link_to "update", edit_restaurant_path %>
<%= link_to "delete", restaurant_path(@restaurant), method: :delete, data: { confirm: "are you sure?" }%>